name: Actualizar precio del aceite desde Infaoliva

on:
  schedule:
    - cron: '0 12 * * *'  # Todos los días a las 12:00 UTC (~14:00 hora local España)
  workflow_dispatch:

jobs:
  actualizar:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Instalar dependencias
      run: pip install beautifulsoup4 requests

    - name: Ejecutar scraper.py
      run: python scraper.py

    - name: Configurar Git
      run: |
        git config user.name "github-actions"
        git config user.email "actions@github.com"

    - name: Confirmar y subir cambios
      run: |
        git add precio-aceite.json
        git commit -m "Actualizar precio desde Infaoliva automáticamente"
        git pull --rebase
        git push
