name: Actualizar precio del aceite

on:
  workflow_dispatch:          # Ejecutar manualmente
  schedule:
    - cron: '0 11 * * *'      # 11:00 UTC = 13:00 España

jobs:
  actualizar:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Instalar dependencias
        run: |
          pip install requests beautifulsoup4 playwright
          python -m playwright install --with-deps chromium

      - name: Ejecutar scraper (Playwright)
        run: python scraper.py

      - name: Ver JSON generado
        run: |
          echo "Contenido de precio-aceite.json:"
          cat precio-aceite.json

      - name: Confirmar cambios en Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git pull --rebase
          git add precio-aceite.json
          git commit -m "Actualizar precio automáticamente (Infaoliva, Playwright)" || echo "No hay cambios para confirmar"
          git push
        continue-on-error: true

      - name: Disparar redeploy en Netlify (Build Hook)
        if: ${{ success() }}
        env:
          BUILD_HOOK: ${{ secrets.NETLIFY_BUILD_HOOK_URL }}
        run: |
          if [ -z "$BUILD_HOOK" ]; then
            echo "No hay NETLIFY_BUILD_HOOK_URL configurado. Sáltate este paso."
            exit 0
          fi
          echo "Lanzando redeploy en Netlify…"
          curl -X POST -d '{}' "$BUILD_HOOK"
