// app.js

const TIPO_LABEL = {
  virgen_extra: 'Aceite de oliva virgen extra',
  virgen: 'Aceite de oliva virgen',
  lampante: 'Aceite de oliva lampante',
};

let PRECIOS_MAP = {};

function setTexto(el, txt) {
  if (el) el.textContent = txt;
}

function euros(n) {
  return `${Number(n).toFixed(3)} €/kg`;
}

function normalizaPrecios(preciosRaw) {
  const map = {};
  if (preciosRaw['Aceite de oliva virgen extra']?.precio_eur_kg) map.virgen_extra = preciosRaw['Aceite de oliva virgen extra'].precio_eur_kg;
  if (preciosRaw['Aceite de oliva virgen']?.precio_eur_kg) map.virgen = preciosRaw['Aceite de oliva virgen'].precio_eur_kg;
  if (preciosRaw['Aceite de oliva lampante']?.precio_eur_kg) map.lampante = preciosRaw['Aceite de oliva lampante'].precio_eur_kg;
  return map;
}

function renderTabla(preciosRaw) {
  const cont = document.getElementById('tabla-precios');
  if (!cont) return;
  cont.innerHTML = `
    <table class="price-table">
      <thead>
        <tr><th>Tipo de aceite de oliva</th><th>Precio €/kg</th></tr>
      </thead>
      <tbody>
        ${Object.entries(preciosRaw).map(([tipo, info]) => `
          <tr>
            <td class="tipo">${tipo}</td>
            <td class="precio">${info.precio_eur_kg ? euros(info.precio_eur_kg) : '—'}</td>
          </tr>
        `).join('')}
      </tbody>
    </table>
  `;
}

function actualizarPrecioSeleccion() {
  const sel = document.getElementById('tipo');
  const precioEl = document.getElementById('precio');
  const key = sel.value;
  const precio = PRECIOS_MAP[key];
  if (precio) setTexto(precioEl, `Precio ${TIPO_LABEL[key]}: ${euros(precio)}`);
  else setTexto(precioEl, '');
}

function calcular() {
  const sel = document.getElementById('tipo');
  const res = document.getElementById('resultado');
  const rEl = document.getElementById('rendimiento');
  const key = sel.value;
  const rendimiento = Number(rEl.value);
  const precio = PRECIOS_MAP[key];

  if (!key || !precio || isNaN(rendimiento) || rendimiento <= 0 || rendimiento > 100) {
    res.classList.add('error');
    res.innerHTML = "Introduce rendimiento válido (0–100) y una calidad.";
    return;
  }

  const precioAceituna = (rendimiento / 100) * precio;
  res.classList.remove('error');
  res.innerHTML = `
    <table class="calc-table">
      <thead>
        <tr>
          <th>Rendimiento (%)</th>
          <th>Calidad del Aceite</th>
          <th>Precio del Aceite</th>
          <th>Precio aceituna (€/kg)</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>${rendimiento}%</td>
          <td>${TIPO_LABEL[key]}</td>
          <td>${euros(precio)}</td>
          <td><strong>${precioAceituna.toFixed(3)} €/kg</strong></td>
        </tr>
      </tbody>
    </table>
  `;
}

async function cargarDatos() {
  const fechaEl = document.getElementById('fecha');
  try {
    const res = await fetch(`precio-aceite.json?v=${Date.now()}`, { cache: 'no-store' });
    const datos = await res.json();

    PRECIOS_MAP = normalizaPrecios(datos.precios || {});
    renderTabla(datos.precios || {});

    const sel = document.getElementById('tipo');
    if (sel && !sel.value) {
      if (PRECIOS_MAP.virgen_extra) sel.value = 'virgen_extra';
      else if (PRECIOS_MAP.virgen) sel.value = 'virgen';
      else if (PRECIOS_MAP.lampante) sel.value = 'lampante';
    }

    actualizarPrecioSeleccion();
    calcular();

    sel?.addEventListener('change', () => { actualizarPrecioSeleccion(); calcular(); });
    document.getElementById('rendimiento')?.addEventListener('input', calcular);

    setTexto(fechaEl, datos.fecha || 'desconocida');
  } catch (err) {
    setTexto(fechaEl, 'Error cargando datos');
  }
}

document.addEventListener('DOMContentLoaded', cargarDatos);
