name: Actualizar precio del aceite

on:
  schedule:
    - cron: '30 11 * * *'   # 11:30 UTC = 13:30 España (ajústalo si quieres)
  workflow_dispatch:
    inputs:
      force_fail:
        description: 'Forzar fallo del job (true/false)'
        required: false
        default: 'false'

permissions:
  contents: write

jobs:
  actualizar:
    runs-on: ubuntu-latest

    steps:
      # ✅ Interruptor para forzar fallo y comprobar la alerta por Gmail
      - name: Forzar fallo si está activado
        if: ${{ github.event.inputs.force_fail == 'true' }}
        run: |
          echo "Fallo forzado a petición del usuario." >&2
          exit 1

      - name: Checkout (repo completo)
        uses: actions/checkout@v4
        with:
          persist-credentials: false     # usaremos tu token personal para el push
          fetch-depth: 0

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Instalar dependencias (Playwright + Chromium)
        run: |
          pip install requests beautifulsoup4 playwright
          python -m playwright install --with-deps chromium

      - name: Ejecutar scraper (Playwright)
        run: python scraper.py

      - name: Ver JSON generado
        run: |
          echo "Contenido de precio-aceite.json:"
          cat precio-aceite.json

      - name: Preparar commit (pull, add, commit)
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git pull --rebase || echo "Sin cambios en remoto"
          git add precio-aceite.json
          git commit -m "Actualizar precio automáticamente (Infaoliva, Playwright)" || echo "No hay cambios para confirmar"

      - name: Hacer push con token personal (SCRAPERGITHUB)
        env:
          TOKEN: ${{ secrets.SCRAPERGITHUB }}
        run: |
          set -e
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}.git
          git push origin HEAD:main
          echo "Último commit en esta rama:"
          git log -1 --oneline

      - name: Disparar redeploy en Netlify (Build Hook) — siempre
        if: ${{ always() }}
        env:
          BUILD_HOOK: ${{ secrets.NETLIFY_BUILD_HOOK_URL }}
        run: |
          if [ -z "$BUILD_HOOK" ]; then
            echo "NETLIFY_BUILD_HOOK_URL no está configurado; salto el redeploy."
            exit 0
          fi
          echo "Lanzando redeploy en Netlify…"
          curl -i -X POST -H "Content-Type: application/json" --data '{}' "$BUILD_HOOK"

  # 🔴 Alerta por Gmail si CUALQUIER paso de 'actualizar' falla
  alertar_fallo:
    needs: [actualizar]
    runs-on: ubuntu-latest
    if: ${{ failure() }}
    steps:
      - name: Enviar alerta por Gmail (mensaje en rojo)
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.GMAIL_USERNAME }}
          password: ${{ secrets.GMAIL_APP_PASSWORD }}
          subject: "⚠️ FALLÓ el scraper de Infaoliva"
          to: ${{ secrets.GMAIL_USERNAME }}
          from: "Scraper Infaoliva <${{ secrets.GMAIL_USERNAME }}>"
          content_type: text/html
          html_body: |
            <div style="font-family:Arial,Helvetica,sans-serif;color:#b00020;">
              <h2 style="color:#b00020;margin:0 0 8px 0;">⚠️ SCRAPER INFAOLIVA: ERROR</h2>
              <p style="color:#b00020;margin:0 0 6px 0;">
                Ha fallado la ejecución del workflow <strong>“Actualizar precio del aceite”</strong>.
              </p>
              <p style="color:#b00020;margin:0 0 6px 0;">
                Revisa los logs en GitHub Actions para ver el motivo (tabla no encontrada, timeouts, precios inválidos, etc.).
              </p>
              <p style="color:#b00020;margin:0;">
                Repo: <strong>${{ github.repository }}</strong><br/>
                Run ID: <strong>${{ github.run_id }}</strong><br/>
                URL del run: 
                <a style="color:#b00020;" href="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}">
                  Abrir logs
                </a>
              </p>
            </div>
