name: Actualizar precio del aceite

on:
  schedule:
    - cron: '30 11 * * *'   # 11:30 UTC = 13:30 España
  workflow_dispatch:

permissions:
  contents: write

jobs:
  actualizar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (con credenciales y repo completo)
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Mostrar remotos y rama
        run: |
          pwd
          git remote -v
          git branch -vv

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Instalar dependencias (Playwright + Chromium)
        run: |
          pip install requests beautifulsoup4 playwright
          python -m playwright install --with-deps chromium

      - name: Ver JSON ANTES del scraper (si existe)
        run: |
          echo "---- JSON antes ----"
          if [ -f precio-aceite.json ]; then cat precio-aceite.json; else echo "no existe"; fi

      - name: Ejecutar scraper (Playwright)
        run: python scraper.py

      - name: Ver JSON DESPUÉS del scraper
        run: |
          echo "---- JSON después ----"
          cat precio-aceite.json

      - name: Preparar commit (add -> stash -> pull --rebase -> stash pop -> commit)
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git status
          git add precio-aceite.json
          git status
          git stash || echo "Nada que guardar en stash"
          git pull --rebase || echo "Sin cambios en remoto / rebase omitido"
          git stash pop || echo "Nada que restaurar de stash"
          git status
          git diff --staged || true
          git commit -m "Actualizar precio automáticamente (Infaoliva, Playwright)" || echo "No hay cambios para confirmar"

      - name: Hacer push (con token)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          # Fuerza a usar el token en https
          git config url."https://x-access-token:${GITHUB_TOKEN}@github.com/".insteadOf "https://github.com/"
          git push origin HEAD:main
          echo "Último commit en esta rama:"
          git log -1 --oneline

      - name: Disparar redeploy en Netlify (Build Hook) — siempre
        if: ${{ always() }}
        env:
          BUILD_HOOK: ${{ secrets.NETLIFY_BUILD_HOOK_URL }}
        run: |
          if [ -z "$BUILD_HOOK" ]; then
            echo "❌ Falta NETLIFY_BUILD_HOOK_URL en Secrets."
            exit 0
          fi
          echo "🚀 Lanzando redeploy en Netlify…"
          curl -i -X POST -H "Content-Type: application/json" --data '{}' "$BUILD_HOOK"
