name: Actualizar precio del aceite

on:
  schedule:
    - cron: '0 6 * * *'  # Todos los días a las 6:00 UTC
  workflow_dispatch:     # Permite ejecutarlo manualmente

jobs:
  actualizar:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Instalar dependencias
        run: pip install requests beautifulsoup4

      - name: Ejecutar scraper
        run: python scraper.py

      - name: Confirmar cambios
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git pull --rebase
          git add precio-aceite.json
          git commit -m "Actualizar precio automáticamente"
          git push
        continue-on-error: true
