name: Actualizar precio del aceite

on:
  schedule:
    - cron: '30 11 * * *'   # 11:30 UTC = 13:30 España (ajusta si quieres)
  workflow_dispatch:

# 👇 Permisos explícitos para poder hacer push
permissions:
  contents: write

jobs:
  actualizar:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4
        with:
          persist-credentials: true  # usa GITHUB_TOKEN para push
          fetch-depth: 0             # necesario para rebase/push correcto

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Instalar dependencias (Playwright + Chromium)
        run: |
          pip install requests beautifulsoup4 playwright
          python -m playwright install --with-deps chromium

      - name: Ejecutar scraper (Playwright)
        run: python scraper.py

      - name: Ver JSON generado
        run: |
          echo "Contenido de precio-aceite.json:"
          cat precio-aceite.json

      - name: Preparar commit
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git status
          git pull --rebase
          git add precio-aceite.json
          git commit -m "Actualizar precio automáticamente (Infaoliva, Playwright)" || echo "No hay cambios para confirmar"

      - name: Hacer push (sin continuar en error)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          git push origin HEAD:main
          git log -1 --oneline

      # ⚠️ Redeploy SIEMPRE (aunque no hubiera cambios de precio)
      - name: Disparar redeploy en Netlify (Build Hook) — siempre
        if: ${{ always() }}
        env:
          BUILD_HOOK: ${{ secrets.NETLIFY_BUILD_HOOK_URL }}
        run: |
          if [ -z "$BUILD_HOOK" ]; then
            echo "❌ NETLIFY_BUILD_HOOK_URL no está configurado en los Secrets del repo."
            exit 0
          fi
          echo "🚀 Lanzando redeploy en Netlify…"
          curl -i -X POST -H "Content-Type: application/json" --data '{}' "$BUILD_HOOK"
