name: Actualizar precio del aceite

on:
  schedule:
    - cron: '30 11 * * *'  # Todos los días a las 13:30 hora de España (11:30 UTC)
  workflow_dispatch:

jobs:
  actualizar:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Instalar dependencias
        run: |
          pip install requests beautifulsoup4 playwright
          python -m playwright install chromium

      - name: Ejecutar scraper
        run: python scraper.py

      - name: Ver JSON generado
        run: |
          echo "Contenido de precio-aceite.json:"
          cat precio-aceite.json

      - name: Confirmar cambios
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git pull --rebase
          git add precio-aceite.json
          git commit -m "Actualizar precio automáticamente desde Infaoliva" || echo "No hay cambios para confirmar"
          git push
        continue-on-error: true

      - name: Disparar redeploy en Netlify (Build Hook)
        if: ${{ success() }}
        env:
          BUILD_HOOK: ${{ secrets.NETLIFY_BUILD_HOOK_URL }}
        run: |
          if [ -z "$BUILD_HOOK" ]; then
            echo "❌ Build hook no configurado en secretos."
            exit 0
          fi
          echo "🚀 Lanzando redeploy en Netlify..."
          curl -i -X POST -H "Content-Type: application/json" --data '{}' "$BUILD_HOOK"
